enum BookingEvents {
  SHOW_DATE_PICKER,
  HIDE_DATE_PICKER,
  DATE_SELECTED,
  TIME_SELECTED,
  RESCHEDULING_BOOKING,
  BOOKING_RESCHEDULED,
  PROCESSING,
  DONE_PRECESSING,
  UPDATE_BOOKING_DATA,
  BOOKINGS_FETCHED,
  GET_ONGOING_BOOKINGS,
  GET_HISTORY_BOOKINGS,
  CANCELLING_BOOKING,
  BOOKING_CANCELLED
}
