name: the_pet_nest
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.5+25
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1
  flutter_rating_bar: ^4.0.0
  flutter_svg: ^0.22.0
  shared_preferences: ^2.0.5
  package_info: ^2.0.0
  intl: ^0.17.0
  flutter_flavor: ^2.0.0
  http: ^0.13.3
  flutter_bloc: ^7.0.1
  dropdown_search: ^0.6.3
  paytm_allinonesdk: ^1.0.0
  flutter_config: ^2.0.0
  google_maps_flutter: ^2.0.6
  geolocator: ^7.3.1
  equatable: ^2.0.0
  shimmer: ^2.0.0
  image_picker: ^0.8.4
  webview_flutter: ^2.0.12
  flutter_html: ^2.1.2
  onesignal_flutter: ^3.0.0
  url_launcher: ^6.0.9
  share: ^2.0.4



dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/map_style/style.txt
    - assets/the_pet_nest.png
    - assets/login_bg.jpg
    - assets/images/india_icon.png
    - assets/placeholder.png
    - assets/skillindia.png
    - assets/pettrainingimage.png
    - assets/vetimage.png
    - assets/petgroomingimage.png
    - assets/blueServiceCardBg.png
    - assets/orangeServiceCardBg.png
    - assets/images/hamburger.svg
    - assets/images/avatar.png
    - assets/images/dog_avatar.svg
    - assets/images/cat_avatar.svg
    - assets/images/home/pet_grooming.svg
    - assets/images/home/pet_training.svg
    - assets/images/home/vet_on_call.svg
    - assets/images/home/refer_n_earn.svg
    - assets/images/home/arogya_setu_icon.svg
    - assets/images/home/one_time_product_icon.svg
    - assets/images/home/sanatise_icon.svg
    - assets/images/home/temp_icon.svg
    - assets/images/home/pet_service_heading.svg
    - assets/images/home/how_it_work.svg
    - assets/images/home/pet_hero_placeholder.svg
    - assets/images/pet_paw_icon.svg
    - assets/images/welcome/hero_image.svg
    - assets/images/bottomNavigation/me_icon.svg
    - assets/images/bottomNavigation/me_fill_icon.svg
    - assets/images/bottomNavigation/invite_icon.svg
    - assets/images/bottomNavigation/invite_fill_icon.svg
    - assets/images/bottomNavigation/home_icon.svg
    - assets/images/bottomNavigation/home_fill_icon.svg
    - assets/images/bottomNavigation/booking_icon.svg
    - assets/images/bottomNavigation/booking_fill_icon.svg
    - assets/images/bottomNavigation/message_icon.svg
    - assets/images/bottomNavigation/message_fill_icon.svg
    - assets/images/sidebar/login.svg
    - assets/images/sidebar/logout.svg
    - assets/images/sidebar/privacyPolicy.svg
    - assets/images/sidebar/referNearn.svg
    - assets/images/sidebar/registerAsPetPartner.svg
    - assets/images/sidebar/shop.svg
    - assets/images/sidebar/support.svg
    - assets/images/sidebar/tnc.svg
    - assets/images/sidebar/icon_no_coupon.svg
    - assets/images/bookings/no_bookings.svg
    - assets/images/bookings/dog_placeholder.svg
    - assets/images/bookings/cat_placeholder.svg
    - assets/images/feedback/empty_star.svg
    - assets/images/feedback/message_icon.svg
    - assets/images/feedback/location.svg
    - assets/images/feedback/placeholder.svg
    - assets/images/profile/edit.svg
    - assets/images/profile/coupons.svg
    - assets/images/profile/service_address.svg
    - assets/images/profile/icon_invitation.svg
    - assets/images/profile/icon_signup.svg
    - assets/images/profile/icon_reward.svg
    - assets/images/profile/icon_share_link.svg
    - assets/images/profile/icon_facebook.png
    - assets/images/profile/icon_whatsapp.png
    - assets/images/profile/dog_avatar.png
    - assets/images/support/support_banner.svg
    - assets/images/support/mail.svg
    - assets/images/support/phone.svg
    - assets/images/support/whatsapp.svg
    - assets/images/login/cat_image.svg
    - assets/images/login/dog_image.svg
    - assets/images/funnels/icon_home.svg
    - assets/images/funnels/icon_add_home.svg
    - assets/images/funnels/package_cost_bg.png
    - assets/images/funnels/icon_payment_cash.svg
    - assets/images/funnels/icon_payment_online.svg
    - assets/images/funnels/grooming_prep_image.png
    - assets/images/funnels/booking_page_coupon_icon.svg
    - assets/images/funnels/icon_booking_confirmed.svg
    - assets/images/funnels/icon_confirm_cancel.svg
    - assets/images/funnels/icon_booking_cancelled.svg
    - assets/images/funnels/icon_booking_cancel.svg
    - assets/images/funnels/icon_booking_detail.svg
    - assets/images/funnels/icon_booking_done.svg
    - assets/images/funnels/icon_booking_reschedule.svg
    - assets/images/funnels/icon_booking_congratulation.svg
    - assets/images/funnels/icon_okay_bg_faded.svg
    - assets/images/funnels/bg_image_coupon.png
    - assets/images/funnels/vet_service/icon_general_medical.svg
    - assets/images/funnels/vet_service/icon_diarrhea.svg
    - assets/images/funnels/vet_service/icon_ear_infection.svg
    - assets/images/funnels/vet_service/icon_loss_of_appetite.svg
    - assets/images/funnels/vet_service/icon_throwing_up.svg
    - assets/images/funnels/vet_service/icon_behavioral.svg
    - assets/images/funnels/vet_service/icon_hair.svg
    - assets/images/funnels/vet_service/icon_injury.svg
    - assets/images/funnels/vet_service/icon_dental.svg
    - assets/images/funnels/vet_service/icon_other.svg
    - assets/images/funnels/vet_service/icon_question.svg
    - assets/images/funnels/vet_service/icon_tell_more.svg
    - assets/images/funnels/vet_service/icon_vet_expert.svg
    - assets/images/funnels/vet_service/vet_service_hero.png
    - assets/images/funnels/vet_service/icon_talk_to_behaviorist.svg
    - assets/images/funnels/vet_service/talk_to_nutritionist.svg
    - assets/images/funnels/pet_training/pet_training_hero.png
    - assets/images/funnels/pet_training/management_techniques.svg
    - assets/images/funnels/pet_training/mental_stimulation.svg
    - assets/images/funnels/pet_training/socialization.svg
    - assets/images/funnels/pet_training/city_list.svg
    - assets/images/funnels/pet_training/strengten_bond.svg
    - assets/images/funnels/pet_grooming/pet_grooming_hero.png
    - assets/images/funnels/pet_grooming/how_it_works_1.svg
    - assets/images/funnels/pet_grooming/how_it_works_2.svg
    - assets/images/funnels/pet_grooming/how_it_works_3.svg
    - assets/images/funnels/pet_grooming/how_it_works_4.svg
    - assets/images/map/map_pin.png
    - assets/images/address/icon_office.svg
    - assets/images/address/icon_map_pin.svg
    - assets/images/messages/img_no_msg.svg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
