enum DateTimeEvent {
  DATE_SELECTED_BY_USER,
  TIME_SELECTED_BY_USER,
  FETCHING_DATE_AVAILABLE,
  DATE_FETCHED,
  SHOW_DATE_TIME_PICKER,
  HIDE_DATE_TIME_PICKER,
  RESET_STATE_VALUE,
  FETCHING_BOOKED_TIME_LIST,
  BOOKED_TIME_LIST_FETCHED,
  TIME_UPDATED
}
