enum CouponEvent {
  GETTING_COUPON_LIST,
  FETCHED_COUPON_LIST,
  COUPON_SELECTED,
  COUPON_CODE_APPLIED,
  COPY_COUPON_CODE,
  APPLYING_COUPON,
  COUPON_APPLIED,
  ERROR_APPLYING_COUPON,
  ERROR_MSG
}
