enum PetProfileEvent {
  FETCHING_PET_DETAIL,
  PET_DETAILS_LOADED,
  ADDING_PET,
  UPDATING_PET_DETAIL,
  PET_DETAILS_CHANGED,
  PETS_BREED_FETCHED,
  PET_ADDED,
  PET_UPDATED,
  ERROR_RESPONSE,
  APP_VERSION_UPDATED,
  PET_ID_SET,
  SHOW_PET_CATEGORY_POPUP,
  SHOW_PET_DETAIL_POPUP,
  SHOW_ADDED_PET_POPUP,
  CANCEL_PET_POPUP,
  SHOW_PET_POPUP
}
