enum UserProfileEvents {
  EMAIL_CHANGED,
  EMAIL_VALID,
  EMAIL_INVALID,
  NAME_CHANGED,
  NAME_VALID,
  NAME_INVALID,
  SUBMITTED,
  UPDATE_SUCCESS,
  UPDATE_FAILED,
  UPDATE_DATA_FROM_STORE,
  IMAGE_SELECTED
}
