enum AddressBookEvent {
  ADDING_NEW_ADDRESS,
  ADDRESS_BOOK_UPDATED,
  FETCHING_ADDRESS_BOOK,
  DELETING_FROM_ADDRESS_BOOK,
  MAP_POS_UPDATED,
  LOCATION_ERROR,
  MAP_MARKER_UPDATED,
  BOTTOM_SHEET_SWIPE,
  BOTTOM_SHEET_MAXIMIZE,
  BOTTOM_SHEET_RESTORE,
  ADDRESS_FIELDS_UPDATED,
  STATES_N_CITIES_LIST_FETCHED,
}
