enum AddressBookEvent {
  ADDING_NEW_ADDRESS,
  NEW_ADDRESS_ADDED,
  ADDRESS_BOOK_UPDATED,
  FETCHING_ADDRESS_BOOK,
  DELETING_FROM_ADDRESS_BOOK,
  MAP_POS_UPDATED,
  LOCATION_ERROR,
  MAP_MARKER_UPDATED,
  BOTTOM_SHEET_SWIPE,
  BOTTOM_SHEET_MAXIMIZE,
  BOTTOM_SHEET_RESTORE,
  ADDRESS_FIELDS_UPDATED,
  STATES_N_CITIES_LIST_FETCHED,
  OPEN_ADD_EDIT_ADDRESS_SCREEN,
  CITY_SELECTED_FROM_DROPDOWN,
  ADDRESS_SELECTED_FROM_LIST
}
