enum PackageEvent {
  FETCHING_PACKAGE_LIST,
  PACKAGE_LIST_FETCHED,
  PACKAGE_SELECTED_BY_USER,
  RESET_STATE_VALUE,
  CLOSE_VALUE_ADDED,
  OPEN_VALUE_ADDED,
  CLOSE_REQUIREMENTS,
  OPEN_REQUIREMENTS,
  PARENTING_PACKAGE_SELECTED,
  VET_PACKAGE_SELECTED
}
